<a href="https://colab.research.google.com/github/Ester-Taniya/DI-Bootcamp/blob/main/Week6/Day1/EX_w6_d1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🌟 Exercise 1 : Array Creation And Manipulation

Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
import numpy as np
NumPy_array_1D = np.arange(10)

NumPy_array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟Exercise 2 : Type Conversion And Array Operations

Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output: array([3, 2, 0, 1, 2])

In [17]:
A_list =  [3.14, 2.17, 0, 1, 2]
NumPy_array = np.array(A_list, dtype=int)
NumPy_array


array([3, 2, 0, 1, 2])

🌟 Exercise 3 : Working With Multi-Dimensional Arrays

Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
NumPy_array = np.arange(1,10)

array_3x3 = NumPy_array.reshape(3, 3)
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [26]:
NumPy_array_2D = np.round(np.random.rand(4, 5), 2)

NumPy_array_2D

array([[0.06, 0.24, 0.93, 0.72, 0.37],
       [0.62, 0.03, 0.43, 0.52, 0.74],
       [0.08, 0.76, 0.36, 0.5 , 0.43],
       [0.79, 0.75, 0.84, 0.21, 0.23]])

🌟 Exercise 5 : Indexing Arrays

Instructions

Select the second row from a given 2D NumPy array.

Expected Output:



array([20, 21, 22, 23, 24])

In [27]:

NumPy_array_2D = np.array([[10, 11, 12, 13, 14],
                     [20, 21, 22, 23, 24],
                     [30, 31, 32, 33, 34],
                      [40, 41, 42, 43, 44],])

second_row = NumPy_array_2D[1, :]

second_row

array([20, 21, 22, 23, 24])

🌟 Exercise 6 : Reversing Elements

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
NumPy_array_1D = np.arange(10)
Reverse_array=NumPy_array_1D[::-1]
Reverse_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix

Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
identity_matrix_4x4 = np.eye(4)

identity_matrix_4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs

Instructions

Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

In [31]:
NumPy_array_1D = np.arange(10)
sum_array = np.sum(NumPy_array_1D)
average_array = np.mean(NumPy_array_1D)

print("Sum:", sum_array, ", Average:", average_array)



Sum: 45 , Average: 4.5


🌟 Exercise 9 : Create Array And Change Its Structure

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
NumPy_array=np.arange(1,21)
matrix_4x5 = NumPy_array.reshape(4, 5)
matrix_4x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection Of Values

Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])

In [38]:
NumPy_array = np.arange(1,10)
odd_numbers = NumPy_array[NumPy_array% 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])